# Exporting Data to SQL Server

In [57]:
# imports pandas, a package for data manipulation and analysis
import pandas as pd  

# imports pyodbc, an open source Python package that makes accessing ODBC databases simple
import pyodbc

# imports sqlalchemy, a SQL toolkit that gives application developers the full power and flexibility of SQL
import sqlalchemy

In [58]:
# imports a sample Super Store dataset provided by Tableau
SuperStoreData = pd.read_csv(r'C:\Users\timen\Documents\Data Sets\SuperStoreData.csv')

In [59]:
SuperStoreData.head(5)

,Days to Ship Actual,Sales Forecast,Ship Status,Days to Ship Scheduled,Sales per Customer,Profit Ratio,Category,City,Country,Customer Name,...,Profit,Quantity,Region,Profit per Order,Sales,Segment,Ship Date,Ship Mode,State,Sub-Category
0,3,392.0,Shipped On Time,3,261.96,16.00%,Furniture,Henderson,United States,Claire Gute,...,42.0,2,South,41.91,$262.00,Consumer,11/11/2016,Second Class,Kentucky,Bookcases
1,3,1096.0,Shipped On Time,3,731.94,30.00%,Furniture,Henderson,United States,Claire Gute,...,220.0,3,South,219.58,$732.00,Consumer,11/11/2016,Second Class,Kentucky,Chairs
2,4,22.0,Shipped Late,3,14.62,47.00%,Office Supplies,Los Angeles,United States,Darrin Van Huff,...,7.0,2,West,6.87,$15.00,Corporate,6/16/2016,Second Class,California,Labels
3,7,1434.0,Shipped Late,6,957.58,-40.00%,Furniture,Fort Lauderdale,United States,Sean O'Donnell,...,-383.0,5,South,-383.03,$958.00,Consumer,10/18/2015,Standard Class,Florida,Tables
4,7,33.0,Shipped Late,6,22.37,11.30%,Office Supplies,Fort Lauderdale,United States,Sean O'Donnell,...,3.0,2,South,2.52,$22.00,Consumer,10/18/2015,Standard Class,Florida,Storage

In [60]:
# sets up an engine for an SQLAlchemy application, defining how to connect with a database
engine = sqlalchemy.create_engine("mssql+pyodbc://enallst:Space72446@SQLServerConnectionExample")

In [61]:
# exports the dataset to a table called "SuperStoreDataFromPython" under the database associated with the ODBC connection
SuperStoreData.to_sql("SuperStoreDataFromPython", con=engine, if_exists='replace', index_label='index')

# Querying Data from SQL Server

In [62]:
# queries data from the same table containing the sample Super Store data
query1 = "SELECT * FROM [master].[dbo].[SuperStoreDataFromPython]"
SuperStoreData = pd.read_sql(query1, engine)

SuperStoreData.head()

,index,Days to Ship Actual,Sales Forecast,Ship Status,Days to Ship Scheduled,Sales per Customer,Profit Ratio,Category,City,Country,...,Profit,Quantity,Region,Profit per Order,Sales,Segment,Ship Date,Ship Mode,State,Sub-Category
0,0,3,392.0,Shipped On Time,3,261.96,16.00%,Furniture,Henderson,United States,...,42.0,2,South,41.91,$262.00,Consumer,11/11/2016,Second Class,Kentucky,Bookcases
1,1,3,1096.0,Shipped On Time,3,731.94,30.00%,Furniture,Henderson,United States,...,220.0,3,South,219.58,$732.00,Consumer,11/11/2016,Second Class,Kentucky,Chairs
2,2,4,22.0,Shipped Late,3,14.62,47.00%,Office Supplies,Los Angeles,United States,...,7.0,2,West,6.87,$15.00,Corporate,6/16/2016,Second Class,California,Labels
3,3,7,1434.0,Shipped Late,6,957.58,-40.00%,Furniture,Fort Lauderdale,United States,...,-383.0,5,South,-383.03,$958.00,Consumer,10/18/2015,Standard Class,Florida,Tables
4,4,7,33.0,Shipped Late,6,22.37,11.30%,Office Supplies,Fort Lauderdale,United States,...,3.0,2,South,2.52,$22.00,Consumer,10/18/2015,Standard Class,Florida,Storage

In [63]:
# another query from the table containing the sample Super Store data; a more proper SQL code layout is shown
query2 = """
SELECT * 
FROM [master].[dbo].[SuperStoreDataFromPython]
WHERE [Ship Status] = 'Shipped Late' AND Profit > '6'
"""

SuperStoreData2 = pd.read_sql(query2, engine)

SuperStoreData2.head()

,index,Days to Ship Actual,Sales Forecast,Ship Status,Days to Ship Scheduled,Sales per Customer,Profit Ratio,Category,City,Country,...,Profit,Quantity,Region,Profit per Order,Sales,Segment,Ship Date,Ship Mode,State,Sub-Category
0,2,4,22.0,Shipped Late,3,14.62,47.00%,Office Supplies,Los Angeles,United States,...,7.0,2,West,6.87,$15.00,Corporate,6/16/2016,Second Class,California,Labels
1,16,7,997.0,Shipped Late,6,665.88,2.00%,Office Supplies,Madison,United States,...,13.0,6,Central,13.32,$666.00,Consumer,11/18/2014,Standard Class,Wisconsin,Storage
2,19,5,320.0,Shipped Late,3,213.48,7.50%,Technology,San Francisco,United States,...,16.0,3,West,16.01,$213.00,Consumer,9/1/2014,Second Class,California,Phones
3,20,5,34.0,Shipped Late,3,22.72,32.50%,Office Supplies,San Francisco,United States,...,7.0,4,West,7.38,$23.00,Consumer,9/1/2014,Second Class,California,Binders
4,26,4,136.0,Shipped Late,3,90.57,13.00%,Technology,Los Angeles,United States,...,12.0,3,West,11.77,$91.00,Consumer,1/20/2016,Second Class,California,Accessories